#required
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeaffinity-required
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: nginx-na-hard
  template:
    metadata:
      labels:
        app: nginx-na-hard
    spec:
      containers:
        - name: nginx-container 
          image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: env
                  operator: In
                  values:
                    - test