#preffered

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeaffinity-preferred
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: nginx-na-soft
  template:
    metadata:
      labels:
        app: nginx-na-soft
    spec:
      containers:
        - name: nginx-container 
          image: nginx
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: env
                    operator: In
                    values:
                      - dev