- name: loops playbook
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: installation of multiple softwares
      yum: name={{item}} state=present
      with_items:
        - git
        - maven
        - docker
        - httpd
        - nginx
