- name: loops playbook
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: creation of multiple users
      user: name={{item}} state=present
      loop:
        - git
        - maven
        - docker
        - httpd
        - nginx
