apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc #refer in the deployment yml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc