apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    pods: "5"                 # Max 5 pods in dev namespace
    limits.cpu: "1"           # Total CPU limit across all pods
    requests.cpu: "500m"      # Total CPU requests
    requests.storage: "1Gi"   # Total storage requests
