apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-deployment
  labels:
    app: zomato
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: zomato-container
          image: kastrov/zomato
          resources:
            limits:
              cpu: "0.3"
              memory: "200Mi"